site_name: Unreal Ultimate Guides

nav:
    - Home: index.md
    - 'Getting Started with Unreal':
      - 'Unreal from Source Code': 'getting-started/unreal-from-source-code.md'
    - 'Programming':
      - 'Programming': 'programming/programming-guide.md'
      - 'C++':
        - 'Variables': 'programming/cpp/variables.md'
        - 'TArray': 'programming/cpp/tarray.md'
        - 'Struct': 'programming/cpp/struct.md'
        - 'Enum / Bitmask': 'programming/cpp/enumbitmask.md'
        - 'Delegate': 'programming/cpp/delegate.md'
        - 'Reference': 'programming/cpp/reference.md'
        - 'Static Variable': 'programming/cpp/static-variable.md'
        - 'Logging': 'programming/cpp/logging.md'
        - 'UProperty and UFunction': 'programming/cpp/uproperty-ufunction.md'
        - 'Display Priority': 'programming/cpp/display-priority.md'
        - 'String Handling': 'programming/cpp/string.md'
        - 'PREPROCESSOR': 'programming/cpp/preprocessor.md'
    - 'Actor Life-cycle': 'actor-lifecycle.md'
    - 'Plugins': 'plugin.md'
    - 'Articles':
      - 'Controller and Camera - What the difference?': 'articles/controller-and-camera.md'
      - 'Player Camera Manager - Creating Custom Camera Movement': 'articles/player-camera-manager.md'
      - 'Renaming Script': 'articles/rename-script.md'

theme:
  name: material

markdown_extensions:
  - attr_list
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.superfences